# roles/common/tasks/main.yml
---
- name: Groupinstall Development Tools
  yum: name={{ item }} state=present update_cache=yes
  with_items:
    - "@development"

- name: Install a list of tools for common use
  yum:
    name:
      - wget
      - unzip
      - tree
      - openssl
      - openssl-devel
      - nginx
    state: present


- name: Remove firewalld service
  yum:
    name: firewalld
    state: absent

- name: Install iptables-services
  yum:
    name: iptables-services
    state: present


# disabling firewall temporary hack for minikube
- name: Enable iptables service
  service:
    name: iptables
    enabled: no
    state: stopped
